# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(default='tech.jpeg', upload_to='projects/')),
                ('description', models.TextField()),
                ('link', models.CharField(default='site.com', max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
